<a href="https://colab.research.google.com/github/MargarytaKyian/AiLabCollegeKyian/blob/main/LabAI3_4Kyian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# Лаб.№3-4 ШІ. Киян М. ІПЗ-407
import numpy as np
from sklearn import preprocessing

input_data = np.array([[4.9, 9.9, -3.5],
[-2.9, 4.1, 3.3],
[-2.2, 8.8, -6.1],
[3.9, 1.4, 2.2]])

# Бінаризація даних
data_binarized = preprocessing.Binarizer(threshold=2.2).transform(input_data)
print("\n Binarized data:\n", data_binarized)

# Виведення середнього значення та стандартного відхилення
print("\nBEFORE: ")
print("Mean =", input_data.mean(axis=0))
print("Std deviation =", input_data.std(axis=0))

# Виключення середнього
data_scaled = preprocessing.scale(input_data)
print("\nAFTER: ")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))

# Масштабування MinМax
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\nМin max scaled data:\n", data_scaled_minmax)

# Нормалізація даних
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')
print("\nl1 normalized data:\n", data_normalized_l1)
print("\nl2 normalized data:\n", data_normalized_l2)


 Binarized data:
 [[1. 1. 0.]
 [0. 1. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

BEFORE: 
Mean = [ 0.925  6.05  -1.025]
Std deviation = [3.50169602 3.45723878 3.9047247 ]

AFTER: 
Mean = [0.00000000e+00 1.11022302e-16 2.77555756e-17]
Std deviation = [1. 1. 1.]

Мin max scaled data:
 [[1.         1.         0.27659574]
 [0.         0.31764706 1.        ]
 [0.08974359 0.87058824 0.        ]
 [0.87179487 0.         0.88297872]]

l1 normalized data:
 [[ 0.26775956  0.54098361 -0.19125683]
 [-0.2815534   0.39805825  0.32038835]
 [-0.12865497  0.51461988 -0.35672515]
 [ 0.52        0.18666667  0.29333333]]

l2 normalized data:
 [[ 0.42286972  0.85436943 -0.3020498 ]
 [-0.4825966   0.68229174  0.54916164]
 [-0.20125974  0.80503895 -0.55803836]
 [ 0.83129388  0.29841319  0.46893501]]
