<a href="https://colab.research.google.com/github/MargarytaKyian/AiLabCollegeKyian/blob/main/LabAI3_4Kyian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# Лаб.№3-4 ШІ. Киян М. ІПЗ-407
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Завантаження даних з TXT файлу
data = pd.read_csv('/content/data_multivar_nb.txt', sep=",", header=None)

# Перевірка на наявність пропусків
if data.isnull().values.any():
    print("\nЗнайдено пропуски в даних. Видалення рядків з пропусками...")
    data = data.dropna()

# Визначаємо ознаки та мітки
X = data.iloc[:, :-1]  # Всі стовпці, окрім останнього
y = data.iloc[:, -1]    # Останній стовпець як мітка

# Перевірка кількості прикладів у кожному класі
class_counts = y.value_counts()
print("Кількість прикладів у кожному класі:", class_counts)

# Видалення рідкісних класів з менше ніж 2 приклади
if any(class_counts < 2):
    print("\nЗнайдено класи з менше ніж 2 приклади. Видалення таких класів...")
    classes_to_remove = class_counts[class_counts < 2].index
    data = data[~data.iloc[:, -1].isin(classes_to_remove)]
    X = data.iloc[:, :-1]
    y = data.iloc[:, -1]

# Розбиття на тренувальну і тестову вибірки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

# Навчання моделей
# Машина опорних векторів
svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)

# Наївний Байєсівський класифікатор
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
y_pred_nb = nb_model.predict(X_test)

# Оцінка якості моделей
print("\nРезультати для SVM:")
print(classification_report(y_test, y_pred_svm))
print("Точність SVM:", accuracy_score(y_test, y_pred_svm))
print("Матриця плутанини SVM:\n", confusion_matrix(y_test, y_pred_svm))

print("\nРезультати для Наївного Байєса:")
print(classification_report(y_test, y_pred_nb))
print("Точність Наївного Байєса:", accuracy_score(y_test, y_pred_nb))
print("Матриця плутанини Наївного Байєса:\n", confusion_matrix(y_test, y_pred_nb))

# Висновки: Порівняння результатів
print("\nВисновок отриманого результату:")
if accuracy_score(y_test, y_pred_svm) > accuracy_score(y_test, y_pred_nb):
    print("SVM має кращу точність у порівнянні з Наївним Байєсом.")
else:
    print("Наївний Байєс має кращу точність у порівнянні з SVM.")


Кількість прикладів у кожному класі: 2
0    100
1    100
2    100
3    100
Name: count, dtype: int64

Результати для SVM:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        30
           1       1.00      1.00      1.00        30
           2       1.00      0.97      0.98        30
           3       0.97      1.00      0.98        30

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120

Точність SVM: 0.9916666666666667
Матриця плутанини SVM:
 [[30  0  0  0]
 [ 0 30  0  0]
 [ 0  0 29  1]
 [ 0  0  0 30]]

Результати для Наївного Байєса:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        30
           1       1.00      1.00      1.00        30
           2       1.00      0.97      0.98        30
           3       0.97      1.00      0.98        30

    accuracy        